### ISSUE TITLE
Login 클래스에서 질문있습니다. 

### ISSUE THREAD

**Issue by yongki150** [rekyungmin/backend-education#27]
사전에 이미 도서관로그인, 도서관스크래핑은 완료했습니다.
스크래핑에서의 에러처리가 조금더 필요한 상황입니다.
또한, 로그인에서 세션을 어디 등록해둔후, 
로그인을 검증해야하는 곳에서 비교할 수 있도록 하는 부분에서 막혔습니다.
그중 이부분이 궁금합니다.

아래 await add_user_session메서드로 self.request.app["session"]를 인자로 넘겨주었습니다.
(이 부분은 session이라는 키를 새로 만들어서 넘겨준것같습니다. 향후 로그인을 검증하고 넘어가야할 부분에서 비교할 수 있도록 하기 위함인것 같습니다.)

>아래 두 코드 모두 api/auth/login 파일경로입니다.
```
session_id = await add_user_session(
            self.request.app["session"],
            ...
        )
```

그후, generate_id() 해주었는데요. 
해당 메서드를 ctrl + 스페이스바해보니 
1. DBSessionManager
2. BaseSessionManager
3. InMemorySessionManager 중 한개에서 처리하신거 같습니다.
**근데 import 한 모듈에서 어떤 것을 사용했는지 나와있지 않아서 이 부분에서 못찾은것 같습니다.
어떤 모듈의 SessionManager 사용하셨는지 알수 있을까요?**
```
async def add_user_session(
    session_manager,
    ...
) -> str:
    ...
    user_session = UserSession(
        session_id=session_manager.generate_id(),
        ...
    )
```

**Comment by rekyungmin** [comment]
로그인 세션은 인메모리세션에서 관리합니다.

스크래이퍼 작업이 끝났으면 biblebot-scraper로 PR 날려주세요.
